plt.plot(hist.history['loss'], label='Training loss')
plt.plot(hist.history['val_loss'], label='Validation loss')
plt.plot(hist_ex1.history['loss'], label='Training loss (regularized)')
plt.plot(hist_ex1.history['val_loss'], label='Validation loss (regularized)')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid()
plt.show()

plt.plot(hist.history['accuracy'], label='Training accuracy')
plt.plot(hist.history['val_accuracy'], label='Validation accuracy')
plt.plot(hist_ex1.history['accuracy'], label='Training accuracy (regularized)')
plt.plot(hist_ex1.history['val_accuracy'], label='Validation accuracy (regularized)')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.grid()
plt.show()